
        const sentences = [
            { sentence: "How are you today?", hindi: "आप आज कैसे हैं?" },
            { sentence: "Could you help me with this?", hindi: "क्या आप मेरी इसमें मदद कर सकते हैं?" },
            { sentence: "Where is the nearest bus stop?", hindi: "सबसे नजदीकी बस स्टॉप कहाँ है?" },
            { sentence: "I would like a cup of coffee, please.", hindi: "मुझे एक कप कॉफी चाहिए, कृपया।" },
            { sentence: "Have a great day!", hindi: "आपका दिन शुभ हो!" },
            
    { sentence: "How are you today?", hindi: "आप आज कैसे हैं?" },
    { sentence: "Could you help me with this?", hindi: "क्या आप मेरी इसमें मदद कर सकते हैं?" },
    { sentence: "Where is the nearest bus stop?", hindi: "सबसे नजदीकी बस स्टॉप कहाँ है?" },
    { sentence: "I would like a cup of coffee, please.", hindi: "मुझे एक कप कॉफी चाहिए, कृपया।" },
    { sentence: "Have a great day!", hindi: "आपका दिन शुभ हो!" },
    { sentence: "What time is it?", hindi: "समय क्या हुआ है?" },
    { sentence: "Can you pass the salt?", hindi: "क्या आप नमक पास कर सकते हैं?" },
    { sentence: "Where can I find a taxi?", hindi: "मुझे टैक्सी कहाँ मिल सकती है?" },
    { sentence: "I don't understand.", hindi: "मुझे समझ नहीं आ रहा है।" },
    { sentence: "Could you repeat that, please?", hindi: "क्या आप इसे फिर से कह सकते हैं?" },
    { sentence: "What is your name?", hindi: "आपका नाम क्या है?" },
    { sentence: "Where do you live?", hindi: "आप कहाँ रहते हैं?" },
    { sentence: "How old are you?", hindi: "आपकी उम्र कितनी है?" },
    { sentence: "I am from India.", hindi: "मैं भारत से हूँ।" },
    { sentence: "What do you do for a living?", hindi: "आप क्या करते हैं?" },
    { sentence: "Can you help me find the nearest restaurant?", hindi: "क्या आप मुझे पास के रेस्टोरेंट का पता बता सकते हैं?" },
    { sentence: "I am looking for a job.", hindi: "मैं नौकरी की तलाश में हूँ।" },
    { sentence: "How long have you been working here?", hindi: "आप यहाँ कितने समय से काम कर रहे हैं?" },
    { sentence: "I don't speak much English.", hindi: "मुझे ज्यादा इंग्लिश नहीं आती।" },
    { sentence: "Do you speak Hindi?", hindi: "क्या आप हिंदी बोलते हैं?" },
    { sentence: "I am learning English.", hindi: "मैं इंग्लिश सीख रहा हूँ।" },
    { sentence: "How do I get to the airport?", hindi: "मैं एयरपोर्ट कैसे पहुँच सकता हूँ?" },
    { sentence: "It is nice to meet you.", hindi: "आपसे मिलकर खुशी हुई।" },
    { sentence: "Where is the bathroom?", hindi: "बाथरूम कहाँ है?" },
    { sentence: "I am feeling great.", hindi: "मैं अच्छा महसूस कर रहा हूँ।" },
    { sentence: "Can I get a glass of water?", hindi: "क्या मुझे पानी का गिलास मिल सकता है?" },
    { sentence: "What are you doing this weekend?", hindi: "इस सप्ताहांत आप क्या करने वाले हैं?" },
    { sentence: "Let's go for a walk.", hindi: "चलिए एक सैर पर चलते हैं।" },
    { sentence: "I am sorry for the inconvenience.", hindi: "असुविधा के लिए मुझे खेद है।" },
    { sentence: "I will be back soon.", hindi: "मैं जल्द ही वापस आऊँगा।" },
    { sentence: "Can I help you with that?", hindi: "क्या मैं आपकी मदद कर सकता हूँ?" },
    { sentence: "How much does it cost?", hindi: "इसका कितना कीमत है?" },
    { sentence: "Do you have any suggestions?", hindi: "क्या आपके पास कोई सुझाव है?" },
    { sentence: "What is the weather like today?", hindi: "आज मौसम कैसा है?" },
    { sentence: "Can you give me directions?", hindi: "क्या आप मुझे दिशा-निर्देश दे सकते हैं?" },
    { sentence: "It was nice talking to you.", hindi: "आपसे बात करके अच्छा लगा।" },
    { sentence: "I am in a hurry.", hindi: "मैं जल्दी में हूँ।" },
    { sentence: "Where is the nearest hospital?", hindi: "सबसे नजदीकी अस्पताल कहाँ है?" },
    { sentence: "How can I help you?", hindi: "मैं आपकी मदद कैसे कर सकता हूँ?" },
    { sentence: "It was a pleasure meeting you.", hindi: "आपसे मिलकर खुशी हुई।" },
    { sentence: "I am feeling a little tired.", hindi: "मैं थोड़ी थकान महसूस कर रहा हूँ।" },
    { sentence: "What do you think about this idea?", hindi: "इस विचार के बारे में आप क्या सोचते हैं?" },
    { sentence: "Could you show me the way?", hindi: "क्या आप मुझे रास्ता दिखा सकते हैं?" },
    { sentence: "I need to speak with the manager.", hindi: "मुझे प्रबंधक से बात करनी है।" },
    { sentence: "This is my first time here.", hindi: "यहाँ मेरा पहला समय है।" },
    { sentence: "What is your favorite food?", hindi: "आपका पसंदीदा खाना क्या है?" },
    { sentence: "Can you wait for me?", hindi: "क्या आप मेरा इंतजार कर सकते हैं?" },
    { sentence: "It’s a beautiful day today.", hindi: "आज का दिन बहुत सुंदर है।" },
    { sentence: "How do you do?", hindi: "आप कैसे हैं?" },
    { sentence: "Can I borrow your pen?", hindi: "क्या मैं आपका पेन उधार ले सकता हूँ?" },
    { sentence: "I will call you later.", hindi: "मैं आपको बाद में कॉल करूंगा।" },
    { sentence: "What did you do today?", hindi: "आपने आज क्या किया?" },
    { sentence: "This is a bit difficult.", hindi: "यह थोड़ा कठिन है।" },
    { sentence: "I don’t know the answer.", hindi: "मुझे जवाब नहीं पता।" },
    { sentence: "What is the problem?", hindi: "समस्या क्या है?" },
    { sentence: "I am hungry.", hindi: "मुझे भूख लगी है।" },
    { sentence: "Please take a seat.", hindi: "कृपया बैठ जाइए।" },
    { sentence: "Do you have any questions?", hindi: "क्या आपके पास कोई सवाल है?" },
    { sentence: "I need a moment.", hindi: "मुझे एक पल चाहिए।" },
    { sentence: "It’s raining outside.", hindi: "बाहर बारिश हो रही है।" },
    { sentence: "Can you give me some advice?", hindi: "क्या आप मुझे कुछ सलाह दे सकते हैं?" },
    { sentence: "I will be there in five minutes.", hindi: "मैं पांच मिनट में वहाँ पहुँचूँगा।" },
    { sentence: "Please pass the bread.", hindi: "कृपया रोटी पास करें।" },
    { sentence: "I’m sorry for being late.", hindi: "देरी के लिए मुझे खेद है।" },
    { sentence: "Let’s meet at the park.", hindi: "चलिए पार्क में मिलते हैं।" },
    { sentence: "This place is very busy.", hindi: "यह जगह बहुत व्यस्त है।" },
    { sentence: "I think I’m lost.", hindi: "मुझे लगता है मैं खो गया हूँ।" },
    { sentence: "Can you speak slower?", hindi: "क्या आप धीरे बोल सकते हैं?" },
    { sentence: "What is your favorite hobby?", hindi: "आपका पसंदीदा शौक क्या है?" },
    { sentence: "I am going to the market.", hindi: "मैं बाजार जा रहा हूँ।" },
    { sentence: "I can’t find my phone.", hindi: "मैं अपना फोन नहीं ढूँढ पा रहा हूँ।" },
    { sentence: "Do you have a map?", hindi: "क्या आपके पास नक्शा है?" },
    { sentence: "I need to charge my phone.", hindi: "मुझे अपना फोन चार्ज करना है।" },
    { sentence: "Can you recommend a good movie?", hindi: "क्या आप एक अच्छा फिल्म सुझा सकते हैं?" },
    { sentence: "I’m looking for my keys.", hindi: "मैं अपनी चाबियाँ ढूँढ रहा हूँ।" },
    { sentence: "Can you give me a discount?", hindi: "क्या आप मुझे छूट दे सकते हैं?" },
    { sentence: "It’s too expensive.", hindi: "यह बहुत महंगा है।" },
    { sentence: "I need some help with this.", hindi: "मुझे इस काम में कुछ मदद चाहिए।" },
    { sentence: "Let me know if you need anything.", hindi: "अगर आपको कुछ चाहिए तो मुझे बताइए।" },
    { sentence: "I’ll be right back.", hindi: "मैं अभी वापस आ रहा हूँ।" },
    { sentence: "What is the best way to learn English?", hindi: "इंग्लिश सीखने का सबसे अच्छा तरीका क्या है?" },
    { sentence: "I think it’s a good idea.", hindi: "मुझे लगता है कि यह एक अच्छा विचार है।" },
    { sentence: "Can you speak louder?", hindi: "क्या आप ज़्यादा ज़ोर से बोल सकते हैं?" },
    { sentence: "I can’t hear you.", hindi: "मैं आपको सुन नहीं पा रहा हूँ।" },
    { sentence: "Where are you from?", hindi: "आप कहाँ से हैं?" },
    { sentence: "It’s too cold today.", hindi: "आज बहुत ठंड है।" },
    { sentence: "I’m feeling a little sick.", hindi: "मुझे थोड़ा बीमार लग रहा है।" },
    { sentence: "How do you spend your free time?", hindi: "आप अपना फ्री टाइम कैसे बिताते हैं?" },
    { sentence: "Please wait for me.", hindi: "कृपया मेरा इंतजार करें।" },
    { sentence: "Do you like this place?", hindi: "क्या आपको यह जगह पसंद है?" },
    { sentence: "I’m running late.", hindi: "मैं देर से आ रहा हूँ।" },
    { sentence: "I will think about it.", hindi: "मैं इसके बारे में सोचूंगा।" },
    { sentence: "I am feeling better now.", hindi: "अब मुझे बेहतर महसूस हो रहा है।" },
    { sentence: "Is this seat taken?"}, 

        ];

        const vocabulary = [
            { word: "articulate", meaning: "स्पष्ट" },
            { word: "eloquent", meaning: "प्रभावशाली" },
            { word: "fluent", meaning: "धाराप्रवाह" },
        
          
            
    { word: "Abandon", meaning: "त्याग करना" },
    { word: "Ability", meaning: "क्षमता" },
    { word: "Absence", meaning: "अनुपस्थिति" },
    { word: "Accept", meaning: "स्वीकार करना" },
    { word: "Accident", meaning: "दुर्घटना" },
    { word: "Accompany", meaning: "साथ जाना" },
    { word: "Achieve", meaning: "सफल होना" },
    { word: "Action", meaning: "क्रिया" },
    { word: "Active", meaning: "सक्रिय" },
    { word: "Adapt", meaning: "अनुकूलित करना" },
    { word: "Admire", meaning: "प्रशंसा करना" },
    { word: "Adventure", meaning: "साहसिक कार्य" },
    { word: "Affection", meaning: "प्रेम" },
    { word: "Aggressive", meaning: "आक्रामक" },
    { word: "Agree", meaning: "सहमत होना" },
    { word: "Alone", meaning: "अकेला" },
    { word: "Ambition", meaning: "महत्त्वाकांक्षा" },
    { word: "Analyze", meaning: "विश्लेषण करना" },
    { word: "Anger", meaning: "क्रोध" },
    { word: "Annoy", meaning: "परेशान करना" },
    { word: "Apology", meaning: "माफी" },
    { word: "Appreciate", meaning: "समान्यता देना" },
    { word: "Arrive", meaning: "पहुंचना" },
    { word: "Attempt", meaning: "प्रयास करना" },
    { word: "Attract", meaning: "आकर्षित करना" },
    { word: "Balance", meaning: "संतुलन" },
    { word: "Benefit", meaning: "लाभ" },
    { word: "Bitter", meaning: "कड़वा" },
    { word: "Brave", meaning: "बहादुर" },
    { word: "Brilliant", meaning: "प्रतिभाशाली" },
    { word: "Capture", meaning: "पकड़ना" },
    { word: "Cautious", meaning: "सावधान" },
    { word: "Challenging", meaning: "चुनौतीपूर्ण" },
    { word: "Character", meaning: "चरित्र" },
    { word: "Classify", meaning: "वर्गीकृत करना" },
    { word: "Clever", meaning: "चतुर" },
    { word: "Comfort", meaning: "सुविधा" },
    { word: "Confident", meaning: "आत्मविश्वासी" },
    { word: "Confuse", meaning: "भ्रमित करना" },
    { word: "Create", meaning: "सृजन करना" },
    { word: "Crisis", meaning: "संकट" },
    { word: "Curious", meaning: "जिज्ञासु" },
    { word: "Dangerous", meaning: "खतरनाक" },
    { word: "Delicate", meaning: "नाज़ुक" },
    { word: "Deny", meaning: "नकारना" },
    { word: "Depend", meaning: "निर्भर करना" },
    { word: "Describe", meaning: "वर्णन करना" },
    { word: "Disaster", meaning: "आपदा" },
    { word: "Discover", meaning: "खोजना" },
    { word: "Discuss", meaning: "चर्चा करना" },
    { word: "Doubt", meaning: "संदेह" },
    { word: "Education", meaning: "शिक्षा" },
    { word: "Effort", meaning: "प्रयास" },
    { word: "Eliminate", meaning: "हटाना" },
    { word: "Encourage", meaning: "प्रोत्साहित करना" },
    { word: "Enthusiastic", meaning: "उत्साही" },
    { word: "Establish", meaning: "स्थापित करना" },
    { word: "Evaluate", meaning: "मूल्यांकन करना" },
    { word: "Exciting", meaning: "रोमांचक" },
    { word: "Experience", meaning: "अनुभव" },
    { word: "Explore", meaning: "अन्वेषण करना" },
    { word: "Express", meaning: "व्यक्त करना" },
    { word: "Flexible", meaning: "लचीला" },
    { word: "Friendly", meaning: "मित्रवत" },
    { word: "Frustrated", meaning: "निराश" },
    { word: "Generous", meaning: "उदार" },
    { word: "Genuine", meaning: "मूल" },
    { word: "Guilty", meaning: "दोशी" },
    { word: "Happy", meaning: "खुश" },
    { word: "Hardworking", meaning: "मेहनती" },
    { word: "Hate", meaning: "नफ़रत करना" },
    { word: "Healthy", meaning: "स्वस्थ" },
    { word: "Honest", meaning: "ईमानदार" },
    { word: "Hope", meaning: "आशा" },
    { word: "Humorous", meaning: "हास्यप्रद" },
    { word: "Identify", meaning: "पहचानना" },
    { word: "Impressive", meaning: "प्रभावशाली" },
    { word: "Improve", meaning: "सुधारना" },
    { word: "Include", meaning: "शामिल करना" },
    { word: "Inspire", meaning: "प्रेरित करना" },
    { word: "Intelligent", meaning: "बुद्धिमान" },
    { word: "Introduce", meaning: "परिचय देना" },
    { word: "Involve", meaning: "शामिल करना" },
    { word: "Jealous", meaning: "ईर्ष्यालु" },
    { word: "Journey", meaning: "यात्रा" },
    { word: "Joke", meaning: "मजाक" },
    { word: "Joyful", meaning: "आनंदी" },
    { word: "Kind", meaning: "दयालु" },
    { word: "Knowledge", meaning: "ज्ञान" },
    { word: "Lazy", meaning: "आलसी" },
    { word: "Loyal", meaning: "निष्ठावान" },
    { word: "Meaningful", meaning: "अर्थपूर्ण" },
    { word: "Mature", meaning: "परिपक्व" },
    { word: "Memory", meaning: "स्मृति" },
    { word: "Mysterious", meaning: "रहस्यमय" },
    { word: "Natural", meaning: "प्राकृतिक" },
    { word: "Nervous", meaning: "नर्वस" },
    { word: "Opportunity", meaning: "अवसर" },
    { word: "Optimistic", meaning: "आशावादी" },
    { word: "Organize", meaning: "संगठित करना" },
    { word: "Patient", meaning: "धैर्यवान" },
    { word: "Perfect", meaning: "पूर्ण" },
    { word: "Polite", meaning: "विनम्र" },
    { word: "Powerful", meaning: "शक्तिशाली" },
    { word: "Proud", meaning: "गर्वित" },
    { word: "Quick", meaning: "तेज़" },
    { word: "Quiet", meaning: "शांत" },
    { word: "Respect", meaning: "सम्मान" },
    { word: "Responsible", meaning: "ज़िम्मेदार" },
    { word: "Sad", meaning: "उदास" },
    { word: "Selfish", meaning: "स्वार्थी" },
    { word: "Sensitive", meaning: "संवेदनशील" },
    { word: "Shy", meaning: "संकोची" },
    { word: "Silly", meaning: "मूर्ख" },
    { word: "Smart", meaning: "स्मार्ट" },
    { word: "Strange", meaning: "अजीब" },
    { word: "Successful", meaning: "सफल" },
    { word: "Sympathetic", meaning: "सहानुभूतिशील" },
    { word: "Talented", meaning: "प्रतिभाशाली" },
    { word: "Tolerant", meaning: "सहनशील" },
    { word: "Trustworthy", meaning: "विश्वसनीय" },
    { word: "Ugly", meaning: "बदसूरत" },
    { word: "Unique", meaning: "विशिष्ट" },
    { word: "Valuable", meaning: "मूल्यवान" },
    { word: "Vulnerable", meaning: "सुरक्षित नहीं" },
    { word: "Warm", meaning: "गर्म" },
    { word: "Wise", meaning: "बुद्धिमान" },
    { word: "Worry", meaning: "चिंता करना" },
    { word: "Young", meaning: "युवा" },
    { word: "Zealous", meaning: "उत्साही" },
];

        

        function generateRandomSentence() {
            const randomIndex = Math.floor(Math.random() * sentences.length);
            const randomSentence = sentences[randomIndex];
            document.getElementById('sentence-display').textContent = `${randomSentence.sentence} - ${randomSentence.hindi}`;
        }

        function generateRandomVocab() {
            const randomIndex = Math.floor(Math.random() * vocabulary.length);
            const randomWord = vocabulary[randomIndex];
            document.getElementById('vocab-display').textContent = `${randomWord.word} - ${randomWord.meaning}`;
        }

        function startSpeechRecognition() {
            const recognition = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
            recognition.lang = 'en-US';
            recognition.start();

            recognition.onresult = (event) => {
                const speechResult = event.results[0][0].transcript;
                document.getElementById('speech-output').textContent = `You said: "${speechResult}"`;
            };

            recognition.onerror = () => {
                document.getElementById('speech-output').textContent = 'Sorry, I could not understand. Please try again.';
            };
        }
    
  

